## Apend

In [17]:
list = [1,2,3,4]
list.append(5)
print(list)


[1, 2, 3, 4, 5]


## Count

In [8]:
list = [1,2,3,4,4,4,5,5,2,1,]
print(list.count(4))

3


## Extend

In [10]:
list = [1,2,3,4]
list.extend([6,5])
print(list)

[1, 2, 3, 4, 6, 5]


## Pop

In [21]:
list.remove(2)

## numpy array

In [ ]:
import numpy
myarr1=numpy.array([10,20,30])
myarr2=numpy.array([[10,20,30],[40,50,60],[70,80,90]])
print(myarr1)
print(myarr2)
print(numpy.shape(myarr1))
print(numpy.shape(myarr2))
print((myarr1.itemsize))
print((myarr2.itemsize))
print((myarr1.ndim))
print((myarr2.ndim))
import numpy as np
numpy.__version__
arr0=np.zeros((2,2))
arr1=np.ones((5,5))
print(arr0)
print(arr1)
arrang_arr=np.arange(3,12,2)
print(arrang_arr)

[10 20 30]
[[10 20 30]
 [40 50 60]
 [70 80 90]]
(3,)
(3, 3)
8
8
1
2
[[0. 0.]
 [0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[ 3  5  7  9 11]


## numpy.random.rand()

In [11]:
import numpy as np
x=np.random.rand(2,5)
x

array([[0.41863436, 0.52208029, 0.6228839 , 0.6105649 , 0.97116044],
       [0.45730906, 0.32539949, 0.55703757, 0.00802202, 0.1302159 ]])

In [ ]:
import numpy as np
x=np.random.randint(5,10,size=(4,5))
print(x)
print(x.ndim) # tells the dimensions like 1D,2D,3D
print(x.shape) # tells the size n*m
print(type(x))

[[8 9 5 8 8]
 [5 7 7 8 6]
 [7 5 7 8 5]
 [9 9 5 6 8]]
2
(4, 5)
<class 'numpy.ndarray'>


## Accessing elements from an array

In [5]:
a1=np.array([[1,2,3,4],[5,6,7,8]])
print(a1)
print(a1[1:,2:]) #indexing forom which it has to print 
a1[-1][2]

NameError: name 'np' is not defined